language: c
compiler: gcc
sudo: true
dist: trusty
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo DEBIAN_FRONTEND=noninteractive install -qq build-essential gnome-common libglib2.0-dev libgtk-3-dev libgee-0.8 libjson-glib-1.0.0 libjson-glib-dev

script:
  - make
