language: generic

services:
  - docker

install:
  - docker build -t dockery .

script:
  - chmod +x ci/make-test-coverage.sh 
  - docker run --privileged --volume=$(pwd):/dockery dockery "ci/make-test-coverage.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash)