language: generic

services:
  - docker

install:
  - docker pull lcallarec/dockery:meson-build

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --volume=$(pwd):/dockery lcallarec/dockery:meson-build /bin/bash -c "/usr/bin/meson -D b_coverage=true build"
  - docker run $ci_env --volume=$(pwd):/dockery lcallarec/dockery:meson-build /bin/bash -c "/usr/bin/meson configure -Dtravis=true -Ddebug=true build"
  - docker run --volume=$(pwd):/dockery lcallarec/dockery:meson-build /bin/bash -c "/usr/bin/meson test -C build --wrapper=xvfb-run"
  - docker run --volume=$(pwd):/dockery lcallarec/dockery:meson-build /bin/bash -c "xvfb-run make test-coverage"
  - docker run $ci_env --volume=$(pwd):/dockery lcallarec/dockery:meson-build /bin/bash -c "bash <(curl -s https://codecov.io/bash)"
