language: c
compiler: gcc
sudo: true
dist: trusty
before_install:
  #- sudo add-apt-repository ppa:vala-team/ppa -y
  #- sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  #- sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  #- sudo apt-get update -y
  - sudo DEBIAN_FRONTEND=noninteractive apt-get --purge remove -y postgresql-9.1 || echo "package 9.1 not found"
  - sudo DEBIAN_FRONTEND=noninteractive apt-get --purge remove -y postgresql-9.2 || echo "package 9.2 not found"
  - sudo DEBIAN_FRONTEND=noninteractive apt-get --purge remove -y postgresql-9.3 || echo "package 9.3 not found"
  - sudo DEBIAN_FRONTEND=noninteractive apt-get --purge remove -y postgresql-9.4 || echo "package 9.4 not found"
  - sudo DEBIAN_FRONTEND=noninteractive apt-get --purge autoremove -y
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade
  - sudo DEBIAN_FRONTEND=noninteractive install -qq build-essential gnome-common libglib2.0-dev libgtk-3-dev libgee-0.8 libjson-glib-1.0.0 libjson-glib-dev
  #sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install -qq build-essential gnome-common libglib2.0-dev libgtk-3-dev libgee-0.8 libjson-glib-1.0.0 libjson-glib-dev
  #       libvala-0.22-dev valac-0.22 
script:
  - make
