language: c
compiler: gcc
sudo: required
dist: xenial
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install -y xvfb build-essential gnome-common valac libglib2.0-dev libgtk-3-dev libgee-0.8-dev libjson-glib-dev libsoup2.4-dev libvte-2.91-dev
after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - NO_AT_BRIDGE=1 TRAVIS=true xvfb-run make
  - NO_AT_BRIDGE=1 TRAVIS=true xvfb-run make test-coverage
