language: generic

services:
  - docker

install:
  - docker build -t dockery .

script:
  - docker run --volume=$(pwd):/dockery dockery "ci/make-test-coverage.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash)